# Eigenvalues and Eigenvectors

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib notebook


$$\vec{A} = 
\begin{pmatrix}
 11 &  -1 & 0\\
-1 &  12 & -1\\
 0 &  -1 & 11
\end{pmatrix}
$$

Find the eigenvalues and eigenvectors for the equation:

$$(\vec{A} - \lambda\vec{I})\vec{v} = 0,$$
where $\vec{v}$ are the eigenvectors and $\lambda$ is the eigenvalues

In [2]:
A = np.array([[11,-1,0], [-1,12,-1], [0,-1,11]])
print(A)

[[11 -1  0]
 [-1 12 -1]
 [ 0 -1 11]]


In [4]:
w,v = np.linalg.eig(A)
print('E-value:', w)
print('E-vector:', v)


#find eigenvaules and eigenvectors

E-value: [13. 11. 10.]
E-vector: [[-4.08248290e-01 -7.07106781e-01  5.77350269e-01]
 [ 8.16496581e-01  4.32017282e-16  5.77350269e-01]
 [-4.08248290e-01  7.07106781e-01  5.77350269e-01]]
